site_name: HRI User Docs
site_url: https://eskrr.github.io/hri_docs/site/
theme:
  name: null
  custom_dir: custom_theme/
nav:
  - '@Home HRI': index.md
  - 'User manual': user_manual.md
repo_url: https://github.com/AYM1607/AtHomeHRI